name: tamely
description: Tamely application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+27

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.1
  provider: ^5.0.0
  http: ^0.13.3
  lottie: ^1.0.1

  url_launcher: ^6.0.7
  image_picker: ^0.8.1+1
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.0.2
  equatable: ^2.0.3

  shimmer: ^2.0.0


  #apple sign in
  sign_in_with_apple: ^3.3.0
  apple_sign_in: ^0.1.0

  #carousel slider
  carousel_slider: ^4.0.0

  #slider indicator
  smooth_page_indicator: ^1.0.0+2

  # staggered grid view
  flutter_staggered_grid_view: ^0.4.0

  #  for sliding images
  flutter_swiper: ^1.1.6

  #  get location
  geolocator: ^8.0.3
  geocoder: ^0.2.1

  #  image cropper
  image_cropper: ^1.4.1

  #  Auto complete text
  flutter_typeahead: ^3.2.1

  #celebration widget
  confetti: ^0.6.0

  #  dotted outline border
  dotted_border: ^2.0.0+1

  # state management
  stacked: ^2.2.5
  stacked_hooks: ^0.2.1

  # navigationr
  stacked_services: ^0.8.8
  stacked_themes:
    path: stacked_themes
  shared_preferences: ^2.0.6

  # inversion of control
  injectable:
  flutter_hooks: ^0.17.0
  observable_ish: ^3.0.0

  # data models
  freezed_annotation: ^1.1.0
  json_annotation: ^4.3.0
  google_sign_in: ^5.1.0

  retrofit: ^3.0.1
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1

  built_value: ^8.1.1
  path_provider: ^2.0.2
  logger: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_lints: ^1.0.4

  #camera: ^0.9.2+2
  video_player: ^2.2.5
  camera: ^0.9.4
  permission_handler: ^8.3.0
  clickable_list_wheel_view: ^0.0.4
  crop_your_image: ^0.6.0+1

  #maps:
  google_maps_flutter: ^2.1.1

  #firebase
  firebase_crashlytics: ^2.2.1
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.1.0
  firebase_remote_config: ^1.0.4
  cloud_firestore: ^3.1.5
  flutter_local_notifications: ^9.0.3
  flutter_facebook_auth: ^4.0.1
  font_awesome_flutter: ^9.2.0

  # for date scroller
  date_picker_timeline: ^1.2.3

  # for date
  intl: ^0.17.0

  #for payment
  razorpay_flutter: ^1.2.7
  new_version: ^0.3.0

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true

flutter_gen:
  output: lib/gen_assets/
  lineLength: 80

  # Optional
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

  flutter_app_name: ^0.1.0


  build_runner:
  flutter_gen_runner: ^4.1.2
  stacked_generator: ^0.5.6


  # data models
  freezed: ^1.1.0
  json_serializable: ^6.0.1
  retrofit_generator: ^3.0.1+1
  built_value_generator: ^8.1.3



flutter_app_name:
  name: "Petmojo"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/emoji/
    - assets/images/service_opening/
    - assets/images/animal_type_images/
    - assets/images/service_page_images/
    - assets/images/animals/
    - assets/images/community_page_images/
    - assets/images/on_boarding/
    - assets/lottie/

  fonts:
    - family: lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf
          weight: 500
        - asset: assets/font/Lato-Light.ttf
          weight: 300
        - asset: assets/font/Lato-Thin.ttf
          weight: 200
        - asset: assets/font/Lato-Bold.ttf
          weight: 700

