name: tamely
description: Tamely application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^0.22.0
  provider: ^5.0.0
  http: ^0.13.3
  lottie: ^1.0.1

  url_launcher: ^6.0.7
  image_picker: ^0.8.1+1
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.0.4

  # staggered grid view
  flutter_staggered_grid_view: ^0.4.0

  #  for sliding images
  flutter_swiper: ^1.1.6

  #  get location
  geolocator: ^7.7.1

  #  Auto complete text
  flutter_typeahead: ^3.2.1

  # state management
  stacked: ^2.1.9
  stacked_hooks: ^0.2.1

  # navigation
  stacked_services: ^0.8.8
  stacked_themes: ^0.3.6
  shared_preferences: ^2.0.6

  # inversion of control
  injectable:
  flutter_hooks: ^0.17.0
  observable_ish: ^3.0.0

  # data models
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  google_sign_in: ^5.1.0

  retrofit: ^2.0.1
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  built_value: ^8.1.1
  path_provider: ^2.0.2
  logger: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_lints: ^1.0.4
#  camera: ^0.9.2+2

  #firebase
  firebase_crashlytics: ^2.2.1
  firebase_core: ^1.6.0
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^10.0.7
  firebase_remote_config: ^0.11.0
  flutter_local_notifications: ^8.2.0
#  flutter_facebook_login: ^3.0.0
#  flutter_statusbarcolor_ns: ^0.4.0
  flutter_facebook_auth: ^3.5.6

flutter_icons:
  image_path: assets/images/light_splash_screen.png
  android: true
  ios: true

flutter_gen:
  output: lib/gen_assets/
  lineLength: 80

  # Optional
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

  build_runner:
  flutter_gen_runner:
  stacked_generator: ^0.5.1

  # data models
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0
  built_value_generator: ^8.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animal_type_images/
    - assets/images/animals/
    - assets/lottie/

  fonts:
    - family: lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf
          weight: 500
        - asset: assets/font/Lato-Light.ttf
          weight: 300
        - asset: assets/font/Lato-Thin.ttf
          weight: 200
        - asset: assets/font/Lato-Bold.ttf
          weight: 700

