import 'package:tamely/ui/profilepage/create_animal_profile/create_animal_view_model.dart';

import 'ImageConstant.dart';

enum AnimalTypes {
  dog,
  cat,
  horse,
  bird,
  rabbit,
  pig,
  hamster,
  insect,
}

enum AnimalCategory {
  Pet,
  Stray,
  Wild,
  Farm,
}

List<String> animalRelations = ["Father", "Mother", "Siblings", "Friend", "NA"];

List<String> availableBreedList = [
  "dog",
  "cat",
  "horse",
  "bird",
  "rabbit",
  "pig",
  "fish",
  "guinea pig",
  "hamster",
  "insect",
];

final List<String> otherAnimalTypesList = [
  "Dog",
  "Cat",
  "Horse",
  "Birds",
  "Rabbit",
  "Pig",
  "Fish",
  "Guinea pigs",
  "Cow",
  "Ox",
  "donkey",
  "goat",
  "llama",
  "alpaca",
  "sheep",
  "goat",
  "elephant",
  "monkey",
  "chimpanzee",
  "lion",
  "deer",
  "koala",
  "polar bear",
  "Dog",
  "Cat",
  "Horse",
  "Birds",
  "Rabbit",
  "Pig",
  "Fish",
  "Guinea pigs",
  "Cow",
  "Ox",
  "donkey",
  "goat",
  "llama",
  "alpaca",
  "sheep",
  "goat",
  "elephant",
  "monkey",
  "chimpanzee",
  "lion",
  "deer",
  "koala",
  "polar bear",
  "cheetah",
  "Poultry",
  "Hamsters",
  "Ferrets",
  "Hedgehogs",
  "Pet rats",
  "Gerbils",
  "Squirrel",
  "Sugar Gliders",
  "Chinchillas",
  "Chipmunks",
  "Bearded Dragon",
  "Snakes",
  "Leapord Gecko",
  "Iguana",
  "Turtles",
  "Tortoise",
  "Other Lizards",
  "Frogs & Toads",
  "Snails",
  "Chameleon",
  "Green Anole",
  "Argentine Black and White Tegu",
  "Savannah Monitor",
  "Chicken",
  "Ducks",
  "Turkeys",
  "Geese",
  "Cow",
  "Ox",
  "donkey",
  "goat",
  "llama",
  "alpaca",
  "sheep",
  "goat",
  "camel",
  "elephant",
  "monkey",
  "chimpanzee",
  "lion",
  "deer",
  "koala",
  "polar bear",
  "cheetah",
  "leopard",
  "zebra",
  "giraffe",
  "panda",
  "kangaroo",
  "panther",
  "tiger",
  "jackal",
  "racoon",
  "hippopotamus",
  "gorilla",
  "fox",
  "wolf",
  "antelope",
  "stag",
  "mangoose",
  "Crab",
  "Poultry",
  "Hamsters",
  "Ferrets",
  "Hedgehogs",
  "Pet rats",
  "Gerbils",
  "Squirrel",
  "Sugar Gliders",
  "Chinchillas",
  "Chipmunks",
  "Bearded Dragon",
  "Snakes",
  "Leapord Gecko",
  "Iguana",
  "Turtles",
  "Tortoise",
  "Other Lizards",
  "Frogs & Toads",
  "Snails",
  "Chameleon",
  "Green Anole",
  "Argentine Black and White Tegu",
  "Savannah Monitor",
  "Chicken",
  "Ducks",
  "Turkeys",
  "Geese",
  "Cow",
  "Ox",
  "donkey",
  "goat",
  "llama",
  "alpaca",
  "sheep",
  "goat",
  "camel",
  "elephant",
  "monkey",
  "chimpanzee",
  "lion",
  "deer",
  "koala",
  "polar bear",
  "cheetah",
  "leopard",
  "zebra",
  "giraffe",
  "panda",
  "kangaroo",
  "panther",
  "tiger",
  "jackal",
  "racoon",
  "hippopotamus",
  "gorilla",
  "fox",
  "wolf",
  "antelope",
  "stag",
  "mangoose",
  "Crab",
];

List<String> dogBreedList = [
  'Unknown',
  'Stray/Indie',
  'German Shepherd',
  'French Bulldogs',
  'Retrievers (Labrador)',
  'Retrievers (Golden)',
  'Bulldogs',
  'Poodles',
  'Beagles',
  'Rottweilers',
  'Pugs',
  'Pointers (German Shorthaired)',
  'Shitzhu',
  'Dachshunds',
  'Belgian Malinois',
  'Maltese',
  'Australian Shepherds',
  'Yorkshire Terriers',
  'Boxers',
  'Great Danes',
  'Siberian Huskies',
  'Cavalier King Charles Spaniels',
  'Doberman Pinschers',
  'Miniature Schnauzers',
  'Boston Terriers',
  'Bernese Mountain Dogs',
  'Pomeranians',
  'Havanese',
  'Cane Corso',
  'Spaniels (English Springer)',
  'Shetland Sheepdogs',
  'Brittanys',
  'Spaniels (Cocker)',
  'Miniature American Shepherds',
  'Border Collies',
  'Mastiffs',
  'Chihuahuas',
  'Vizslas',
  'Basset Hounds',
  'Weimaraners',
  'Collies',
  'Newfoundlands',
  'Rhodesian Ridgebacks',
  'Shiba Inu',
  'West Highland White Terriers',
  'Bichons Frises',
  'Bloodhounds',
  'Spaniels (English Cocker)',
  'Akitas',
  'Portuguese Water Dogs',
  'Retrievers (Chesapeake Bay)',
  'Dalmatians',
  'St. Bernards',
  'Papillons',
  'Australian Cattle Dogs',
  'Bullmastiffs',
  'Samoyeds',
  'Scottish Terriers',
  'Soft Coated Wheaten Terriers',
  'Whippets',
  'Pointers (German Wirehaired)',
  'Chinese Shar-Pei',
  'Airedale Terriers',
  'Wirehaired Pointing Griffons',
  'Bull Terriers',
  'Alaskan Malamutes',
  'Cardigan Welsh Corgis',
  'Giant Schnauzers',
  'Old English Sheepdogs',
  'Italian Greyhounds',
  'Great Pyrenees',
  'Dogues de Bordeaux',
  'Russell Terriers',
  'Cairn Terriers',
  'Irish Wolfhounds',
  'Setters (Irish)',
  'Greater Swiss Mountain Dogs',
  'Miniature Pinschers',
  'Lhasa Apsos',
  'Chinese Crested',
  'Coton de Tulear',
  'Staffordshire Bull Terriers',
  'American Staffordshire Terries',
  'Rat Terriers',
  'Chow Chows',
  'Anatolian Shepherd Dogs',
  'Basenjis',
  'Spaniels (Boykin)',
  'Lagotti Romagnoli',
  'Brussels Griffons',
  'Retrievers (Nova Scotia Duck olling)',
  'Norwegian Elkhounds',
  'Standard Schnauzers',
  'Dogo Argentinos',
  'Bouviers des Flandres',
  'Pekingese',
  'Keeshonden',
  'Border Terriers',
  'Leonbergers',
  'Tibetan Terriers',
  'Neapolitan Mastiffs',
  'Setters (English)',
  'Retrievers (Flat-Coated)',
  'Borzois',
  'Fox Terriers (Wire)',
  'Miniature Bull Terriers',
  'Belgian Tervuren',
  'Setters (Gordon)',
  'Silky Terriers',
  'Norwich Terriers',
  'Spinoni Italiani',
  'Japanese Chin',
  'Welsh Terriers',
  'Toy Fox Terriers',
  'Schipperkes',
  'Parson Russell Terriers',
  'Pointers',
  'Belgian Sheepdogs',
  'Tibetan Spaniels',
  'American Eskimo Dogs',
  'Irish Terriers',
  'Beaucerons',
  'Afghan Hounds',
  'Boerboels',
  'Fox Terriers (Smooth)',
  'Bearded Collies',
  'Black Russian Terriers',
  'Black and Tan Coonhounds',
  'Spaniels (Welsh Springer)',
  'American Hairless Terriers',
  'Norfolk Terriers',
  'Xoloitzcuintli',
  'Manchester Terriers',
  'Kerry Blue Terriers',
  'Australian Terriers',
  'Spaniels (Clumber)',
  'Lakeland Terriers',
  'Bluetick Coonhounds',
  'English Toy Spaniels',
  'German Pinschers',
  'Tibetan Mastiffs',
  'Bedlington Terriers',
  'Greyhounds',
  'Pulik',
  'Salukis',
  'Barbets',
  'Redbone Coonhounds',
  'Swedish Vallhunds',
  'Sealyham Terriers',
  'Spanish Water Dogs',
  'Briards',
  'Berger Picards',
  'Entlebucher Mountain Dogs',
  'Treeing Walker Coonhounds',
  'Icelandic Sheepdogs',
  'Wirehaired Vizslas',
  'Pumik',
  'Portuguese Podengo Pequenos',
  'Spaniels (American Water)',
  'Retrievers (Curly-Coated)',
  'Spaniels (Field)',
  'Lowchen',
  'Nederlandse Kooikerhondjes',
  'Affenpinschers',
  'Petits Bassets Griffons Vendens',
  'Finnish Lapphunds',
  'Scottish Deerhounds',
  'Plott Hounds',
  'Norwegian Buhunds',
  'Glen of Imaal Terriers',
  'Setters (Irish Red and White)',
  'Ibizan Hounds',
  'Spaniels (Sussex)',
  'Bergamasco Sheepdogs',
  'Spaniels (Irish Water)',
  'Polish Lowland Sheepdogs',
  'Otterhounds',
  'Kuvaszok',
  'Komondorok',
  'Cirnechi dell’Etna',
  'Pharaoh Hounds',
  'Dandie Dinmont Terriers',
  'Pyrenean Shepherds',
  'Skye Terriers',
  'Canaan Dogs',
  'American English Coonhounds',
  'Chinooks',
  'Finnish Spitz',
  'Grand Basset Griffon Vendeens',
  'Sloughis',
  'Harriers',
  'Cesky Terriers',
  'American Foxhounds',
  'Azawakhs',
  'English Foxhounds',
  'Norwegian Lundehunds',
  'Pomsky',
  'Pitsky',
  'Alusky',
  'Labsky',
  'Goberian',
  'Cockapoo',
  'Bernadoodle',
  'Labradoodle',
  'Corgipoo',
  'Yorkiepoo',
  'Double Doodle',
  'Corgidor',
  'Cavador',
  'Puggle',
  'Frenchie Pug/ Frug',
  'Aussiepom',
  'Chiweenie',
  'Bojack',
  'Border Sheepdog',
  'Beaglier',
  'Papitese',
  'Siberian Retriever',
  'Cavachon',
  'Weimador',
  'Shorkie',
  'Border Collie Sheltie',
  'Chug',
  'Morkie',
  'Shih-Poo',
  'Schnoodle',
  'Whoodle',
  'Mastiff Mix',
  'Docker',
  'Cavapoo',
  'Maltipoo',
  'Springador',
  'Jack-A-Poo',
  'Pugapoo',
  'Gerberian Shepsky',
  'Texas Heeler',
  'Boxerdoodle',
  'Poogle',
  'Utonagan',
  'Cheagle',
  'Bullmation',
  'Docker',
  'Labrastaff',
  'Great Weimer',
  'Labradane',
  'Chusky',
];

List<String> catBreedList = [
  'Unknown',
  'Stray/Indie',
  'Abyssinian',
  'American Bobtail',
  'American Shorthair',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Shorthair',
  'Devon Rex',
  'Domestic Longhair',
  'Exotic Shorthair',
  'Himalayan',
  'Maine Coon',
  'Norwegian Forest',
  'Persian',
  'Ragdoll',
  'Savannah',
  'Scottish Fold',
  'Siamese',
  'Sphynx',
  'York Chocolate',
  'Ukrainian Levkoy',
  'Turkish Vankedisi',
  'Turkish Van',
  'Turkish Angora',
  'Toyger',
  'Tonkinese',
  'Thai',
  'Traditional, Classic, or Old-style Siamese',
  'Wichien Maat[g]',
  'Thai Lilac, Thai Blue Point and Thai Lilac Point',
  'Suphalak',
  'Somali',
  'Sokoke',
  'Snowshoe',
  'Singapura',
  'Siberian',
  'Siberian Forest Cat',
  'Neva Masquerade (colorpoint variety)',
  'Serrade Petit',
  'Serengeti',
  'Selkirk Rex',
  'Sam Sawet',
  'Russian White, Russian Black and Russian Tabby',
  'Russian Blue',
  'Ragamuffinor',
  'Liebling',
  'Raas',
  'Pixie-bob',
  'Peterbald',
  'Persian (traditional)',
  'Persian (modern)',
  'Oriental Shorthair',
  'Oriental Longhair',
  'Oriental Bicolor',
  'Oregon Rex',
  'Ojos Azules',
  'Ocicat',
  'Nebelung',
  'Napoleon',
  'Munchkin',
  'Minskin',
  'Mekong Bobtail',
  'Manx',
  'Lykoi',
  'LaPerm',
  'Lambkin',
  'Kurilian Bobtail or',
  'Kuril Islands Bobtail',
  'Korn Ja',
  'Korean Bobtail',
  'Korat',
  'Kinkalow',
  'Khao Manee',
  'Kanaani',
  'Javanese or',
  'Colorpoint Longhair',
  'Japanese Bobtail',
  'Colorpoint Persian',
  'Highlander',
  'Havana Brown',
  'German Rex',
  'Foldex',
  'European Shorthair',
  'Egyptian Mau',
  'Dwelf',
  'Dragon Li',
  'Chinese Li Hua',
  'Donskoy',
  'Don Sphynx',
  'Cyprus',
  'Cymric, Manx Longhair or Long-haired Manx',
  'Cornish Rex',
  'Colorpoint Shorthair',
  'Chausie',
  'Chartreux',
  'Chantilly-Tiffany',
  'California Spangled',
  'Burmilla',
  'Burmese',
  'British Longhair',
  'Brazilian Shorthair',
  'Bambino',
  'Australian Mist',
  'Asian Semi-longhair',
  'Asian',
  'Arabian Mau',
  'Aphrodite Giant',
  'American Wirehair',
  'American Ringtail',
  'American Curl',
  'Aegean',
];

List<String> horseBreedList = [
  'Unknown',
  'American Quarter Horse',
  'Arabian Horse',
  'Appaloosa',
  'Morgan',
  'Warmblood',
  'Thoroughbred',
  'Ponies',
  'Grade horses',
  'Akhal Teke',
  'Albino',
  'Alter-Real',
  'American Buckskin',
  'American Cream',
  'American Saddlebred',
  'American Standardbred',
  'American Warmblood',
  'American White',
  'Andalusian',
  'Barb',
  'Bashkir Curly',
  'Belgian',
  'Chickasaw',
  'Cleveland Bay',
  'Clydesdale',
  'Connemara',
  'Dales',
  'Dartmoor',
  'Dutch Warmblood',
  'Fell Pony',
  'French Saddle Horse',
  'Friesian (West Friesian)',
  'Gotland (or Skogsruss)',
  'Hackney',
  'Haflinger',
  'Hanoverian',
  'Highland (or Garron)',
  'Holstein',
  'Lipizzaner',
  'Lustiano',
  'Missouri Fox Trotter',
  'Morab',
  'Mustang',
  'New Forest',
  'Norwegian Fjord Pony',
  'Oldenburg',
  'Paint',
  'Palomino',
  'Paso Fino',
  'Percheron',
  'Peruvian Paso',
  'Pinto',
  'Pony of the Americas (POA)',
  'Shetland',
  'Shire',
  'Spanish Barb',
  'Spotted Saddle',
  'Suffolk (or Suffolk Punch)',
  'Swedish Warmblood or Halfbred',
  'Tennessee Walking Horse',
  'Trakehner',
  'Welsh Pony (Sections A, B, C, D)',
  'Wurttemberg',
];

List<String> birdsBreedList = [
  'Unknown',
  'Parakeet/Budgie',
  'Cockatiel',
  'Finch',
  'Lovebird',
  'Monk Parakeet',
  'Dove',
  'Parrotlet',
  'African Gray Parrot',
  'African Pied Hornbill',
  'Budgerigar',
  'Chicken',
  'Conure',
  'African Grey Parrot',
  'Macaw',
  'Sun Conure',
  'Parrot',
  'Owl',
  'Peacock',
  'Amazon',
  'Blue-and-yellow Macaw',
  'Caique',
  'Umbrella Cockatoo',
  'Senegal Parrot',
  'Indian Ringneck',
  'African Pied Hornbill',
  'Accentor',
  'Finch',
  'Aceh Pheasant',
  'Pionus Parrot',
  'Diamond Dove',
  'Quaker',
  'Quacker Parrot',
  'Eclectus Parrot',
  'Yellowhead',
  'Galah Cockatoo',
  'Moluccan Cockatoo',
  "Goffin's Cockatoo",
  'Acorn Woodpecker',
  'Muscovy Duck',
  'peach fronted conure',
  'Campbell Albatross',
  'African Penguin',
  'Adelie Penguin',
  'Blue Crown Conure',
  'American Avocet',
  'Rosella',
  'Goose',
  'Pekin Duck',
  'Pigeon',
  "Meyer's Parrot",
  'Yellow-crowned Parakeet',
  'Scarlett Macaw',
  'Jardine Parrot',
  'African Collared Dove',
  'African Lemon-dove',
  'Yellow Nape Amazon',
];

List<String> rabbitBreedList = [
  'Unknown',
  'Lionhead Rabbit',
  'Flemish Giant',
  'Continental Giant',
  'Dutch Rabbit',
  'English Lop',
  'French Lop',
  'Holland Lop',
  'Mini Rex',
  'Netherland dwarf',
  'Polish Rabbit',
  'American',
  'American Fuzzy Lop',
  'American Sable',
  'Argente Brun',
  'Argente Crème',
  'Argente de Champagne',
  'Belgian Hare',
  'Beveren',
  'Blanc de Hotot',
  'Britannia Petite',
  'Californian',
  'Checkered Giant',
  'Chinchilla (Standard)',
  'Chinchilla (American)',
  'Chinchilla (Giant)',
  'Cinnamon',
  'Dwarf Hotot',
  'Dwarf Lop (Mini Lop in USA)',
  'English Angora',
  'English Spot',
  'Florida White',
  'French Angora',
  'Giant Angora',
  'Giant Papillon',
  'Harlequin',
  'Havana',
  'Himalayan',
  'Jersey Wooly',
  'Lilac',
  'New Zealand',
  'Palomino',
  'Rex (Standard)',
  'Rhinelander',
  'Satin',
  'Satin Angora',
  'Silver',
  'Silver Fox',
  'Silver Marten',
  'Tan',
  'Thrianta',
  'Velveteen Lop',
];

List<String> pigBreedList = [
  'Unknown',
  'Stray/Indie',
  'Aksai Black Pied',
  'American Yorkshire',
  'Angeln Saddleback',
  'Ankamali',
  'Appalachian English',
  'Arapawa pig',
  'Auckland Island',
  'Australian Yorkshire',
  'Babi Kampung',
  'Ba Xuyen',
  'Bantu',
  'Basque',
  'Bazna',
  'Beijing Black',
  'Belarus Black Pied',
  'Belgian Landrace',
  'Bengali Brown Shannaj',
  'Bentham Black Pied',
  'Berkshire',
  'Bisaro',
  'Bangur',
  'Black Slavonian',
  'Black Canarian',
  'Breitovo',
  'British Landrace',
  'British Lop',
  'British Saddleback',
  'Bulgarian White',
  'Cantonese',
  'Celtic',
  'Chato Murciano',
  'Chester White',
  'Chiangmai Blackpig a.k.a. MooDum Chiangmai',
  'Choctaw hog',
  'Creole pig',
  'Czech Improved White',
  'Danish Landrace',
  'Dermantsi Pied',
  'Li Yan',
  'Dharane Kalo sungur',
  'Duroc',
  'Dutch Landrace',
  'East Balkan',
  'Essex',
  'Estonian Bacon',
  'Fengling',
  'Finnish Landrace',
  'Forest Mountain',
  'French Landrace',
  'Gascon',
  'German Landrace',
  'Gloucestershire Old Spots',
  'Göttingen minipig',
  'Grice',
  'Guinea hog',
  'Hampshire',
  'Hante',
  'Hereford',
  'Hezuo',
  'Hogan',
  'Husumer or Danish Protest pig',
  'Huntingdon Black',
  'Iberian',
  'Iron Age pig',
  'Italian Landrace',
  'Japanese Landrace',
  'Jeju Black',
  'Jinhua',
  'Juliana',
  'Kakhetian',
  'Kele',
  'Kemerovo',
  'Korean Native',
  'Krškopoljski',
  'Kunekune',
  'Lacombe',
  'Large Black',
  'Large Black and White',
  'Large White',
  'Latvian White',
  'Leicoma',
  'Linderödssvin',
  'Lithuanian Native',
  'Lithuanian White',
  'Lincolnshire Curly Coat',
  'Livny',
  'Malhado de Alcobaça',
  'Mangalica',
  'Meishan ',
  'Middle White',
  'Minzhu ',
  'Minokawa Buta',
  'Mong Cai',
  'Mora Romagnola',
  'Moura',
  'Mukota',
  'Mulefoot',
  'Murom',
  'Myrhorod',
  'Nero Siciliano',
  'Neijiang',
  'Ningxiang',
  'North Caucasian',
  'North Siberian',
  'Norwegian Landrace',
  'Norwegian Yorkshire',
  'Ossabaw Island hog',
  'Oxford Sandy and Black',
  'Pakchong 5',
  'Philippine Native',
  'Piétrain',
  'Pennywell miniature pig',
  'Poland China',
  'Red Wattle hog',
  'Semirechensk',
  'Siberian Black Pied',
  'Small Black (extinct)',
  'Small White (extinct)',
  'Spots',
  'Surabaya Babi',
  'Sushan pig ',
  'Swabian-Hall',
  'Swedish Landrace',
  'Taihu ',
  'Tamworth',
  'Teacup pig',
  'Tsivilsk',
  'Turopolje',
  'Ukrainian Spotted Steppe',
  'Ukrainian White Steppe',
  'Urzhum',
  'Vietnamese Pot-Bellied',
  'Welsh',
  'Wessex Saddleback',
  'West French White',
  'Windsnyer',
  'Wuzishan',
  'Yanan',
  'Yoga Sir',
];

List<String> fishBreedList = [
  'Unknown',
  'Cory Catfish',
  'Guppies',
  'Mollies',
  'Swordtails',
  'Kuhli Loach',
  'Neon Tetra',
  'Bristlenose Pleco',
  'Betta Fish',
  'Zebra Danio',
  'Dwarf Gourami',
  'Goldfish',
  'Convict Cichlid',
  'African Cichlids',
  'Red Cherry Shrimp',
  'Cherry Barb',
  'Tiger Barb',
  'Oscar Cichlids',
  'Platies',
  'Pearl Gourami',
  'Discus',
  'Killifish',
  'Rainbowfish',
  'Angelfish',
  'Firemouth Cichlids',
  'Pictus Catfish',
  'Clown Loach',
  'Harlequin Rasboras',
  'Marble Hatchetfish',
  'Upside-Down Catfish',
  'White Cloud Minnows',
  'Bichir',
  'old Barb',
  'Rosy Barb',
  'German Blue Ram',
  'Cockatoo Cichlid',
  'Jack Dempsey',
  'Green Texas Cichlid',
  'Odessa Barb',
  'Asian Stone Catfish',
  'Diamond Tetra',
  'Cardinal Tetra',
  'Blood Parrot Cichlid',
  'Rainbow Shark',
  'White Skirt Tetra',
  'Redeye Tetra',
  'Raphael Catfish',
  'Glass Catfish',
  'Otocinclus',
];

List<String> guineaPigBreedList = [
  'Unknown',
  'Guinea Pig Basics',
  'Abyssinian Guinea Pig',
  'Alpaca Guinea Pig',
  'American Guinea Pig',
  'Baldwin Guinea Pig',
  'Coronet Guinea Pig',
  'Himalayan Guinea Pig',
  'Lunkarya Guinea Pig',
  'Merino Guinea Pig',
  'Peruvian Guinea Pig',
  'Rex Guinea Pig',
  'Sheba Guinea Pig',
  'Silkie Guinea Pig',
  'Skinny Guinea Pig',
  'Teddy Guinea Pig',
  'Texel Guinea Pig',
  'White-Crested Guinea Pig',
];

List<String> hamsterBreedList = [
  'Unknown',
  'Armenian Hamster',
  'Chinese Hamster',
  'Chinese Striped Hamster',
  'Ciscaucasian Hamster',
  "Dwarf Campbell's Russian Hamster",
  'Dwarf Winter White Russian Hamster',
  'European Hamster',
  "Eversmann's Hamster",
  'Ladak Hamster',
  'Mongolian Hamster',
  'Lesser Longtailed Hamster',
  'Greater Longtailed Hamster',
  'Mouse-like Hamster',
  'Roborovski Hamster',
  'Rumanian Hamster',
  'Syrian Hamster',
  'Tibetan Hamster',
  'Turkish Hamster',
];

List<String> insectsBreedList = [
  'Unknown',
  'Tarantulas',
  'Stick & Leaf insects',
  'Hissing cockroaches',
  'Scorpions',
  'African Giant Millipedes',
  'Antlions',
  'Praying Mantis',
  'Millipedes',
  'Crickets',
  'Mealworms',
  'Doodlebugs',
  'Ground beetles',
  'Culturing springtails',
  'Rhinoceres beetles',
  'Woodlice',
  'Spiders',
  'Stick bugs',
  'Grasshopper',
  'Phasmid',
  'Superworm',
  'Dubia roach',
  'Speckled cockroach',
  'Venezuelen poodle moth',
  'Blattodea',
  'Holloween moon crabs',
  'Ants',
];

final List<AnimalTypeModel> petAnimalTypeListValues = [
  AnimalTypeModel(
    "Dog",
    dogImgPath,
  ),
  AnimalTypeModel(
    "Cat",
    catImgPath,
  ),
  AnimalTypeModel(
    "Horse",
    horseImgPath,
  ),
  AnimalTypeModel(
    "Birds",
    birdImgPath,
  ),
  AnimalTypeModel(
    "Rabbit",
    rabbitImgPath,
  ),
  AnimalTypeModel(
    "Pig",
    pigImgPath,
  ),
  AnimalTypeModel(
    "Fish",
    fishImgPath,
  ),
  AnimalTypeModel(
    "Guinea pigs",
    guineaPigImgPath,
  ),
  AnimalTypeModel(
    "Hamsters",
    hamstersImgPath,
  ),
];

final List<AnimalTypeModel> strayAnimalTypeListValues = [
  AnimalTypeModel(
    "Dog",
    dogImgPath,
  ),
  AnimalTypeModel(
    "Cat",
    catImgPath,
  ),
  AnimalTypeModel(
    "Horse",
    horseImgPath,
  ),
  AnimalTypeModel(
    "Goat",
    goatImgPath,
  ),
  AnimalTypeModel(
    "Rabbit",
    rabbitImgPath,
  ),
  AnimalTypeModel(
    "Pig",
    pigImgPath,
  ),
  AnimalTypeModel(
    "Camel",
    camelImgPath,
  ),
  AnimalTypeModel(
    "Guinea pigs",
    guineaPigImgPath,
  ),
  AnimalTypeModel(
    "Cow",
    cowImgPath,
  ),
  AnimalTypeModel(
    "Donkeys ",
    donkeyImgPath,
  ),
];

final List<AnimalTypeModel> wildAnimalTypeListValues = [
  AnimalTypeModel(
    "Elephant",
    elephantImgPath,
  ),
  AnimalTypeModel(
    "Monkey",
    monkeyImgPath,
  ),
  AnimalTypeModel(
    "Gorillas",
    gorillaImgPath,
  ),
  AnimalTypeModel(
    "Lion",
    lionImgPath,
  ),
  AnimalTypeModel(
    "Tiger ",
    tigerImgPath,
  ),
  AnimalTypeModel(
    "Deer",
    deerImgPath,
  ),
  AnimalTypeModel(
    "Polar bear",
    polarBearImgPath,
  ),
  AnimalTypeModel(
    "Cheetah",
    cheetahImgPath,
  ),
  AnimalTypeModel(
    "Panda",
    pandaImgPath,
  ),
];

final List<AnimalTypeModel> farmAnimalTypeListValues = [
  AnimalTypeModel(
    "Chicken",
    chickenImgPath,
  ),
  AnimalTypeModel(
    "Cattle",
    cowImgPath,
  ),
  AnimalTypeModel(
    "Sheep",
    sheepImgPath,
  ),
  AnimalTypeModel(
    "Ducks",
    duckImgPath,
  ),
  AnimalTypeModel(
    "Goats",
    goatImgPath,
  ),
  AnimalTypeModel(
    "Alpaca",
    alpacaImgPath,
  ),
  AnimalTypeModel(
    "Pigs",
    pigImgPath,
  ),
  AnimalTypeModel(
    "Horse",
    horseImgPath,
  ),
  AnimalTypeModel(
    "Rabbit",
    rabbitImgPath,
  ),
  AnimalTypeModel(
    "Llama",
    llamaImgPath,
  ),
  AnimalTypeModel(
    "Donkeys",
    donkeyImgPath,
  ),
];
