enum BottomSheetType {
  BasicBottomSheet,
  CommentsBottomSheet,
  MoreOptionBottomSheet,
  AddDetailsBottomSheet,
  SelectAnimalTypeBottomSheet,
  SelectOtherAnimalTypeBottomSheet,
  SelectBreedBottomSheet,
  SubmitApprovalBottomSheet,
  EndWalkBottomSheet,
  ConfirmEndWalkBottomSheet,
  CancelSubscriptionBottomSheet,
  DeletePostBottomSheet,
  BasicListOfOptionsBottomSheet,
}
